pipeline {
    agent any

    environment {
        IMAGE = "ghcr.io/srimaha02/vpc-docker-app"
        TAG   = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh "docker build -t ${IMAGE}:${TAG} -t ${IMAGE}:latest ."
                }
            }
        }

        stage('Push to GHCR') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'ghcr-creds',
                        usernameVariable: 'GH_USER',
                        passwordVariable: 'GH_TOKEN'
                    )
                ]) {
                    sh '''
                        echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin
                        docker push ${IMAGE}:${TAG}
                        docker push ${IMAGE}:latest
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([
    [$class: 'AmazonWebServicesCredentialsBinding',
     credentialsId: 'aws-creds',
     accessKeyVariable: 'AWS_ACCESS_KEY_ID',
     secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']
]) {
                    dir('app/terraform') {
                        sh 'terraform init -input=false'
                        sh 'terraform apply -auto-approve -input=false'
                    }
                }
            }
        }

        stage('Show Output') {
            steps {
                dir('app/terraform') {
                    sh 'terraform output'
                }
            }
        }
    }
}